apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: hello-calendar
spec:
  calendar:
    example:
      interval: 60s
---
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: helloworld-sensor
spec:
  template:
    serviceAccountName: argo-events-sa
  dependencies:
    - name: test-dep
      eventSourceName: hello-calendar
      eventName: example
  triggers:
    - template:
        name: workflow-trigger
        k8s:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: create
          source:
            git:
              url: https://github.com/whynowy/argo-events-workshop
              cloneDirectory: "/tmp"
              filePath: "examples/workflows/helloworld.yaml"


