apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: webhook-example
spec:
  webhook:
    example:
      port: "8080"
      endpoint: /
      method: POST
---
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: sensor-from-url
spec:
  template:
    serviceAccountName: argo-events-sa
  dependencies:
    - name: dep01
      eventSourceName: webhook-example
      eventName: example
  triggers:
    - template:
        name: workflow-trigger
        k8s:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: create
          source:
            url: 
              path: https://raw.githubusercontent.com/whynowy/argo-events-workshop/master/examples/workflows/helloworld.yaml


